Create PayeeFormPage
it-kmitl-2018/group10-frontend pull request #37
Opened 2018-05-14 11:51 UTC by aliveable

# PayerTradePatryForm
## Payer-components
- PayerEmail
- PayerSpecifiedTaxRegistration
- PayerTradeParty
- PayerTradePartyAddress
- PayerTradePartyForm (หน้ารวม 4 อัน บน)
- electronicTaxInvoiceForm (ใว้เรียก PayerTradePartyForm มาแสดงผล  พร้อมใส่ Method Axios.post)
ผมใส่ Data Object ใว้ ทั้ง 2 อันนะครับ เดี็๋ยว Travis ไม่ผ่าน

2018-05-14 12:46 UTC, pangaunn approved these changes

2018-05-14 12:48 UTC, pangaunn requested changes
โทษทีนะอีกนิดนึงตัวแปรใน data อะน่าจะต้องตัวเล็กขึ้นต้นนะ อีกอันด้วย

2018-05-14 14:10 UTC, pangaunn approved these changes
เคครับ ดีงามม

2018-05-15 08:03 UTC, merged

2018-05-20 14:35 UTC, champillon commented
4.25 คะแนน